### ISSUE TITLE
Queens NY address mis-parsed & untrainable

### ISSUE THREAD

**Issue by cds-amal** [datamade/usaddress#101]
Hi,

I'm having trouble with the following address:
Address: 105-25 Horace Harding Expy N, Corona, NY
Corona should be a 'PlaceName'. 

Attempt at parsing:
```
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import usaddress as us
>>> s1 = '105-25 Horace Harding Expy N Corona, Queens, NY'
>>> us.tag(s1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/dev/parsers/addressparser/env_addressparser/local/lib/python2.7/site-packages/usaddress/__init__.py", line 94, in tag
    raise RepeatedLabelError(address_string, parse(address_string), label)
usaddress.RepeatedLabelError:

ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  105-25 Horace Harding Expy N Corona, Queens, NY
PARSED TOKENS:    [(u'105-25', 'AddressNumber'), (u'Horace', 'StreetName'), (u'Harding', 'StreetName'), (u'Expy', 'StreetNamePostType'), (u'N', 'StreetNamePreDirectional'), (u'Corona,', 'StreetName'), (u'Queens,', 'PlaceName'), (u'NY', 'StateName')]
UNCERTAIN LABEL:  StreetName

When this error is raised, it's likely that either (1) the string is not a valid address or (2) some tokens were labeled incorrectly


```

I couldn't get the trainer to work properly with this address - it doesn't pick up the State (NY). 

```
$ cat horaceharding.csv
105-25 Horace Harding Expy N, Corona, NY

$ parserator label horaceharding.csv training/labeled.xml usaddress

1 of 1)
--------------------------------------------------
STRING: 105-25 Horace Harding Expy N
| 105-25  | AddressNumber             |
| Horace  | StreetName                |
| Harding | StreetName                |
| Expy    | StreetNamePostType        |
| N       | StreetNamePostDirectional |
Is this correct? (y)es / (n)o / (s)kip / (f)inish tagging / (h)elp
```

Thanks in advance!

P.S. This library, documentation and support is wonderful! Thank you!

**Comment by cathydeng** [comment]
hey @cds-amal - parserator only grabbed the first part of the string b/c it interpreted `105-25 Horace Harding Expy N`, `Corona`, & `NY` as three separate fields in the csv. this can be fixed by quoting strings that contain commas.

this is a useful training example, I'll add it to the labeled addresses. thanks! :smiley:
