### ISSUE TITLE
unabbreviated street types aren't labeled properly

### ISSUE THREAD

**Issue by miverson** [datamade/usaddress#114]
I've come across a parsing issue when the PlaceName and StreetName are the same, and there is a unit number at the end of the address string. While I can't post the actual address that I used, It is really easy to reproduce with a made up address.

```
>>> fails = '12345 CLEVELAND BOULEVARD #26, CLEVELAND OH 12345-6789'
>>> usaddress.tag(fails)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/usaddress/__init__.py", line 94, in tag
    raise RepeatedLabelError(address_string, parse(address_string), label)
usaddress.RepeatedLabelError:

ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  12345 CLEVELAND BOULEVARD #26, CLEVELAND OH 12345-6789
PARSED TOKENS:    [('12345', 'AddressNumber'), ('CLEVELAND', 'StreetName'), ('BOULEVARD', 'StreetNamePreType'), ('#', 'StreetName'), ('26,', 'StreetName'), ('CLEVELAND', 'PlaceName'), ('OH', 'StateName'), ('12345-6789', 'ZipCode')]
UNCERTAIN LABEL:  StreetName

When this error is raised, it's likely that either (1) the string is not a valid address or (2) some tokens were labeled incorrectly

To report an error in labeling a valid address, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve usaddress!

For more information, see the documentation at http://usaddress.readthedocs.org/
```

These variants also fail:

```
'12345 CLEVELAND BOULEVARD #26, CLEVELAND OH 12345-6789'
'12345 TAMPA BOULEVARD #26, TAMPA FL 12345-6789'
```

However, the following address parses, showing that the repeated city name may be a factor.

```
>>> good = '12345 RIVER BOULEVARD #26, CLEVELAND OH 12345-6789'
>>> usaddress.tag(good)
(OrderedDict([('AddressNumber', '12345'), ('StreetName', 'RIVER'), ('StreetNamePostType', 'BOULEVARD'), ('OccupancyIdentifier', '# 26'), ('PlaceName', 'CLEVELAND'), ('StateName', 'OH'), ('ZipCode', '12345-6789')]), 'Street Address')
```

Also, clearly separating the occupancy identifier with a comma also resolves the issue:

```
>>> good = '12345 CLEVELAND BOULEVARD,  # 26, CLEVELAND OH 12345-6789'
>>> usaddress.tag(good)
(OrderedDict([('AddressNumber', '12345'), ('StreetName', 'CLEVELAND'), ('StreetNamePostType', 'BOULEVARD'), ('OccupancyIdentifier', '# 26'), ('PlaceName', 'CLEVELAND'), ('StateName', 'OH'), ('ZipCode', '12345-6789')]), 'Street Address')
```

Using the more mundane 'ROAD' instead of 'BOULEVARD' makes things parse without an error, but the results are clearly incorrect, with the Occupancy identifier shown as the street name:

```
>>> not_really_good = '12345 TAMPA ROAD #26, TAMPA FL 12345-6789'
>>> usaddress.tag(not_really_good)
(OrderedDict([('AddressNumber', '12345'), ('StreetNamePreType', 'TAMPA ROAD'), ('StreetName', '# 26'), ('PlaceName', 'TAMPA'), ('StateName', 'FL'), ('ZipCode', '12345-6789')]), 'Street Address')

>>> not_really_good = '12345 TAMPA ROAD # 26, TAMPA FL 12345-6789'
>>> usaddress.tag(not_really_good)
(OrderedDict([('AddressNumber', '12345'), ('StreetNamePreType', 'TAMPA ROAD'), ('StreetName', '# 26'), ('PlaceName', 'TAMPA'), ('StateName', 'FL'), ('ZipCode', '12345-6789')]), 'Street Address')

>>> not_really_good = '12345 CLEVELAND ROAD #26, CLEVELAND OH 12345-6789'
>>> usaddress.tag(not_really_good)
(OrderedDict([('AddressNumber', '12345'), ('StreetNamePreType', 'CLEVELAND ROAD'), ('StreetName', '# 26'), ('PlaceName', 'CLEVELAND'), ('StateName', 'OH'), ('ZipCode', '12345-6789')]), 'Street Address')
```

Adding a comma between city and state also make it better:

```
>>> good = '12345 CLEVELAND BOULEVARD # 26, CLEVELAND, OH 12345-6789'
>>> usaddress.tag(good)
(OrderedDict([('AddressNumber', '12345'), ('StreetName', 'CLEVELAND'), ('StreetNamePostType', 'BOULEVARD'), ('OccupancyIdentifier', '# 26'), ('PlaceName', 'CLEVELAND'), ('StateName', 'OH'), ('ZipCode', '12345-6789')]), 'Street Address')
```

Using the 'BLVD' abbreviation will fix the problem as well:

```
>>> good = '12345 TAMPA BLVD #26, TAMPA FL 12345-6789'
>>> usaddress.tag(good)
(OrderedDict([('AddressNumber', '12345'), ('StreetName', 'TAMPA'), ('StreetNamePostType', 'BLVD'), ('OccupancyIdentifier', '# 26'), ('PlaceName', 'TAMPA'), ('StateName', 'FL'), ('ZipCode', '12345-6789')]), 'Street Address')
```

The street name appears to have to be a likely to be a well known city name to trigger the problem, as this parses.

```
>>> good = '12345 RIVER BOULEVARD #26, RIVER OH 12345-6789'
>>> usaddress.tag(good)
(OrderedDict([('AddressNumber', '12345'), ('StreetName', 'RIVER'), ('StreetNamePostType', 'BOULEVARD'), ('OccupancyIdentifier', '# 26'), ('PlaceName', 'RIVER'), ('StateName', 'OH'), ('ZipCode', '12345-6789')]), 'Street Address')
```

EDIT: The fact that the street name is a common city name seems to be more important than the repetition:

```
>>> also_bad = '12345 CLEVELAND BOULEVARD # 26, TAMPA FL 12345-6789'
>>> usaddress.tag(also_bad)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/usaddress/__init__.py", line 94, in tag
    raise RepeatedLabelError(address_string, parse(address_string), label)
usaddress.RepeatedLabelError:

ERROR: Unable to tag this string because more than one area of the string has the same label

ORIGINAL STRING:  12345 CLEVELAND BOULEVARD # 26, TAMPA FL 12345-6789
PARSED TOKENS:    [('12345', 'AddressNumber'), ('CLEVELAND', 'StreetName'), ('BOULEVARD', 'StreetNamePreType'), ('#', 'StreetName'), ('26,', 'StreetName'), ('TAMPA', 'PlaceName'), ('FL', 'StateName'), ('12345-6789', 'ZipCode')]
UNCERTAIN LABEL:  StreetName

When this error is raised, it's likely that either (1) the string is not a valid address or (2) some tokens were labeled incorrectly

To report an error in labeling a valid address, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve usaddress!

For more information, see the documentation at http://usaddress.readthedocs.org/
```

**Comment by cathydeng** [comment]
hey @miverson - this is helpful, thanks for reporting!

this definitely isn't due to StreetName & PlaceName being the same due to how the features are set up, and it doesn't look like it's due to StreetName being a common city name (if that were the case, usaddress would erroneously label the StreetName token as PlaceName, which it's not).

it's more likely that the address parser hasn't seen enough training examples with 'boulevard' or 'road' as the street type - it turns out 'blvd' & 'rd' are much more common in real world addresses. would you be able to send over any address examples w/ street type spelled out (from a real dataset, not made up) for training, to fix this?

**Comment by miverson** [comment]
Unfortunately, privacy regulations will prevent sending live examples. 

How else could I help?

**Comment by fgregg** [comment]
@cathydeng we could do something similar to what we do with `DIRECTIONS` https://github.com/datamade/usaddress/blob/master/usaddress/__init__.py#L155

**Comment by cathydeng** [comment]
yeah that'd work, we could use http://pe.usps.gov/text/pub28/28apc_002.htm

**Comment by fgregg** [comment]
Hi @miverson, added your training data and made some other tweaks. Could you let me know if it works for your data?

**Comment by miverson** [comment]
Sorry for the slow reply, but I will test this.

**Comment by jeancochrane** [comment]
Closing this – feel free to open a new issue if the problem persists @miverson!
