### ISSUE TITLE
IndexError: string index out of range on training/synthetic_osm_data_xml.xml

### ISSUE THREAD

**Issue by chengguangnan** [datamade/usaddress#119]
I tested this on both Python 3.5.1 :: Anaconda 2.4.1 

Master branch 

`parserator train training/synthetic_osm_data_xml.xml    usaddress`

```

training model on 16148 training examples from ['training/synthetic_osm_data_xml.xml']
Traceback (most recent call last):
  File "/Users/chengguangnan/anaconda/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "/Users/chengguangnan/anaconda/lib/python3.5/site-packages/parserator/main.py", line 37, in dispatch
    args.func(args)
  File "/Users/chengguangnan/anaconda/lib/python3.5/site-packages/parserator/main.py", line 66, in train
    training.train(module, train_file_list)
  File "/Users/chengguangnan/anaconda/lib/python3.5/site-packages/parserator/training.py", line 92, in train
    trainModel(training_data, module)
  File "/Users/chengguangnan/anaconda/lib/python3.5/site-packages/parserator/training.py", line 25, in trainModel
    X.append(module.tokens2features(tokens))
  File "/Users/chengguangnan/anaconda/lib/python3.5/site-packages/usaddress-0.5.5-py3.5.egg/usaddress/__init__.py", line 263, in tokens2features
    token_features = tokenFeatures(token)
  File "/Users/chengguangnan/anaconda/lib/python3.5/site-packages/usaddress-0.5.5-py3.5.egg/usaddress/__init__.py", line 235, in tokenFeatures
    features = {'abbrev' : token_clean[-1] == u'.',
IndexError: string index out of range
```

**Comment by chengguangnan** [comment]
Also, how was the default .crfsuite built? Since 'training/*.xml' will throw an error.

**Comment by cathydeng** [comment]
hey @chengguangnan - that's odd, I'll look into it

the default .crfsuite model file is built w/ `parserator train training/labeled.xml usaddress`

& for using a glob pattern w/ parserator, it needs to be quoted, e.g. `parserator train "training/*.xml" usaddress`

**Comment by jeancochrane** [comment]
This looks like it's closed. If the issue returns, let us know!
