### ISSUE TITLE
Unable to train usaddress w/ parserator v 0.4.2

### ISSUE THREAD

**Issue by mpentecost** [datamade/usaddress#131]
When following docs to build and train the model, when attempting to run the first train command:
`vagrant:~/usaddress/usaddress$ parserator train training/labeled.xml usaddress`

I get:

```
training model on 1046 training examples from ['training/labeled.xml']
Traceback (most recent call last):
  File "/home/vagrant/listops_env_3/bin/parserator", line 11, in <module>
    sys.exit(dispatch())
  File "/home/vagrant/listops_env_3/lib/python3.4/site-packages/parserator/main.py", line 54, in dispatch
    args.func(args)
  File "/home/vagrant/listops_env_3/lib/python3.4/site-packages/parserator/main.py", line 81, in train
    training.train(module, train_file_list, modelfile)
  File "/home/vagrant/listops_env_3/lib/python3.4/site-packages/parserator/training.py", line 96, in train
    trainModel(training_data, module, model_file)
  File "/home/vagrant/listops_env_3/lib/python3.4/site-packages/parserator/training.py", line 33, in trainModel
    trainer.train(model_path)
  File "pycrfsuite/_pycrfsuite.pyx", line 359, in pycrfsuite._pycrfsuite.BaseTrainer.train (pycrfsuite/_pycrfsuite.cpp:3857)
  File "stringsource", line 15, in string.from_py.__pyx_convert_string_from_py_std__in_string (pycrfsuite/_pycrfsuite.cpp:9777)
TypeError: expected bytes, NoneType found
```

**Comment by cathydeng** [comment]
hey @mpentecost - sorry about this!

this is an issue w/ parserator - the most recent version of parserator broke training, & we haven't had the time to make a fix yet. see [this thread](https://github.com/datamade/parserator/issues/29) for a temporary duct-tape solution

**Comment by mpentecost** [comment]
Thanks @cathydeng !
I ran:
`pip uninstall parserator && pip install parserator==0.4.1`

And can now train the model:

```
training model on 1021 training examples from ['training/labeled.xml']
done training! model file created: usaddress/usaddr.crfsuite
```

**Comment by cathydeng** [comment]
great! leaving this issue open til we get parserator fixed, for others who wana build the dev code

**Comment by cathydeng** [comment]
fixed via https://github.com/datamade/parserator/commit/ea35e23263f6d942157d65ec5fb7c12f63697260
