### ISSUE TITLE
3121 187th street crt n east moline il 61244 unit test is incorrect

### ISSUE THREAD

**Issue by tebrown** [datamade/usaddress#189]
I am working at adding additional STREET_NAMES in the `usaddress/__init__.py`.  One of the STREET_NAMES I added was 'crt'.  Unfortunately, this caused one of the unit tests to fail.  

This is an unusual address, for certain, but I *think* it should be tagged such that "187th Street" is the street name, and StreetNamePostType is 'crt'.  The reason I believe this to be true is that streets should generally not have multiple StreetNamePostDirectionals.  Obviously, there are going to be exceptions to this rule, but the general training should take care of this.

```
FAIL: test_labeling.TestPerformance.test_all(b'3121 187th street crt n east moline il 61244', ('AddressNumber', 'StreetName', 'StreetName', 'StreetNamePostType', 'StreetNamePostDirectional', 'PlaceName', 'PlaceName', 'StateName', 'ZipCode'), ('AddressNumber', 'StreetName', 'StreetNamePostType', 'StreetNamePostType', 'StreetNamePostDirectional', 'PlaceName', 'PlaceName', 'StateName', 'ZipCode'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/teb/src/usaddress/tests/test_labeling.py", line 63, in equals
    assert labels_pred == labels_true
nose.proxy.AssertionError:
-------------------- >> begin captured stdout << ---------------------
ADDRESS:     b'3121 187th street crt n east moline il 61244'
pred:        ('AddressNumber', 'StreetName', 'StreetName', 'StreetNamePostType', 'StreetNamePostDirectional', 'PlaceName', 'PlaceName', 'StateName', 'ZipCode')
true:        ('AddressNumber', 'StreetName', 'StreetNamePostType', 'StreetNamePostType', 'StreetNamePostDirectional', 'PlaceName', 'PlaceName', 'StateName', 'ZipCode')
````

**Comment by jeancochrane** [comment]
Closed by [ab00738](https://github.com/datamade/usaddress/commit/ab00738b5596876f83a08d8ad53f6ff1c97a509b). Thanks for your work @tebrown!
