### ISSUE TITLE
ERROR: Unable to tag this string because more than one area of the string has the same label

### ISSUE THREAD

**Issue by philiporlando** [datamade/usaddress#359]
I'm encountering tag errors with the following address: `"38350 40TH ST EAST 100 PALMDALE CA 93552"`

```python
import usaddress

address = "38350 40TH ST EAST 100 PALMDALE CA 93552"

usaddress.tag(address)

# Traceback (most recent call last):
#   File "/home/user/usaddress_parse_error/usaddress_parse_error.py", line 5, in <module>
#     usaddress.tag(address)
#   File "/home/user/.cache/pypoetry/virtualenvs/usaddress-parse-error-aadNbsKj-py3.10/lib/python3.10/site-packages/usaddress/__init__.py", line 177, in tag
#     raise RepeatedLabelError(address_string, parse(address_string),
# usaddress.RepeatedLabelError: 
# ERROR: Unable to tag this string because more than one area of the string has the same label

# ORIGINAL STRING:  38350 40TH ST EAST 100 PALMDALE CA 93552
# PARSED TOKENS:    [('38350', 'AddressNumber'), ('40TH', 'StreetName'), ('ST', 'StreetNamePostType'), ('EAST', 'StreetNamePreDirectional'), ('100', 'StreetName'), ('PALMDALE', 'PlaceName'), ('CA', 'StateName'), ('93552', 'ZipCode')]
# UNCERTAIN LABEL:  StreetName

# When this error is raised, it's likely that either (1) the string is not a valid person/corporation name or (2) some tokens were labeled incorrectly

# To report an error in labeling a valid name, open an issue at https://github.com/datamade/usaddress/issues/new - it'll help us continue to improve probablepeople!

# For more information, see the documentation at https://usaddress.readthedocs.io/
```

Fortunately, I'm still able to parse this address: 

```python
import usaddress

address = "38350 40TH ST EAST 100 PALMDALE CA 93552"

print(usaddress.parse(address))

# [('38350', 'AddressNumber'), ('40TH', 'StreetName'), ('ST', 'StreetNamePostType'), ('EAST', 'StreetNamePreDirectional'), ('100', 'StreetName'), ('PALMDALE', 'PlaceName'), ('CA', 'StateName'), ('93552', 'ZipCode')]
```

But I'm unable to use the `scourgify.normalize_address_record()` utility because of the errors related to `usaddress.tag()`:

```python
from scourgify import normalize_address_record

address = "38350 40TH ST EAST 100 PALMDALE CA 93552"

normalize_address_record(address)

# Traceback (most recent call last):
#   File "/home/user/usaddress_parse_error/usaddress_parse_error.py", line 5, in <module>
#     normalize_address_record(address)
#   File "/home/user/.cache/pypoetry/virtualenvs/usaddress-parse-error-aadNbsKj-py3.10/lib/python3.10/site-packages/scourgify/normalize.py", line 159, in normalize_address_record
#     return normalize_addr_str(
#   File "/home/user/.cache/pypoetry/virtualenvs/usaddress-parse-error-aadNbsKj-py3.10/lib/python3.10/site-packages/scourgify/normalize.py", line 267, in normalize_addr_str
#     raise UnParseableAddressError(None, None, addr_rec)
# scourgify.exceptions.UnParseableAddressError: UNPARSEABLE ADDRESS: Unable to break this address into its component parts, OrderedDict([('address_line_1', '38350 40TH ST EAST 100 PALMDALE CA 93552'), ('address_line_2', None), ('city', None), ('state', None), ('postal_code', None)])
```

I originally opened [this issue](https://github.com/GreenBuildingRegistry/usaddress-scourgify/issues/31) on the [usaddress-scourgify repo](https://github.com/GreenBuildingRegistry/usaddress-scourgify), but we have determined that the root cause of the issue is related to `usaddress.tag()` and would prefer to fix upstream. 

Please let me know if you have any questions or need any additional details. Thank you!

**Comment by vinvomero** [comment]
If the main goal is keeping a batch job from dying on inputs like this, fastaddress (a drop-in that runs the same usaddress model in Rust) has a `tag_native()` that returns a best-effort parse instead of raising:

```python
import fastaddress
fastaddress.tag_native("38350 40TH ST EAST 100 PALMDALE CA 93552")
# ({'AddressNumber': '38350', 'StreetName': '40TH 100', 'StreetNamePostType': 'ST',
#   'StreetNamePreDirectional': 'EAST', 'PlaceName': 'PALMDALE', 'StateName': 'CA', 'ZipCode': '93552'}, 'Street Address')
```

Fair warning: it is the same model, so it does not resolve the `100`/`40TH` ambiguity you flagged, it lumps them together as StreetName here. What you get is a result instead of an exception, plus a confidence score to route the shaky ones like this to review rather than wrapping every call in try/except. `pip install fastaddress`.
